2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_setup.py:_flush():68] Configure stats pid to 4465
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_setup.py:_flush():68] Loading settings from /home/fritzprix/.config/wandb/settings
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_setup.py:_flush():68] Loading settings from /home/fritzprix/my_work/ml_note/labs/simple_ml/wandb/settings
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'labs/simple_ml/train.py', 'program': '/home/fritzprix/my_work/ml_note/labs/simple_ml/train.py'}
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:_log_setup():476] Logging user logs to /home/fritzprix/my_work/ml_note/labs/simple_ml/wandb/run-20230120_130813-30ni7tuv/logs/debug.log
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:_log_setup():477] Logging internal logs to /home/fritzprix/my_work/ml_note/labs/simple_ml/wandb/run-20230120_130813-30ni7tuv/logs/debug-internal.log
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:init():516] calling init triggers
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:init():569] starting backend
2023-01-20 13:08:13,279 INFO    MainThread:4465 [wandb_init.py:init():573] setting up manager
2023-01-20 13:08:13,280 INFO    MainThread:4465 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-01-20 13:08:13,282 INFO    MainThread:4465 [wandb_init.py:init():580] backend started and connected
2023-01-20 13:08:13,283 INFO    MainThread:4465 [wandb_init.py:init():658] updated telemetry
2023-01-20 13:08:13,284 INFO    MainThread:4465 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-01-20 13:08:13,741 INFO    MainThread:4465 [wandb_run.py:_on_init():2006] communicating current version
2023-01-20 13:08:13,775 INFO    MainThread:4465 [wandb_run.py:_on_init():2010] got version response upgrade_message: "wandb version 0.13.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-01-20 13:08:13,775 INFO    MainThread:4465 [wandb_init.py:init():728] starting run threads in backend
2023-01-20 13:08:14,672 WARNING MainThread:4465 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 739, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 235, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 486, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 255, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 36, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-01-20 13:08:19,772 WARNING MsgRouterThr:4465 [router.py:message_loop():77] message_loop has been closed
