/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py:396: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(
Found cached dataset wikitext (/home/fritzprix/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 931.45it/s]
Loading cached processed dataset at /home/fritzprix/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126/cache-fa4a4a4c04b58af6.arrow
Loading cached processed dataset at /home/fritzprix/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126/cache-73a6c9a57c86a67d.arrow
Loading cached processed dataset at /home/fritzprix/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126/cache-18725908dcba4345.arrow

100%|████████████████████████████████████████████████████████████████████████████████████████████████| 23767/23767 [00:02<00:00, 8324.62ex/s]

100%|███████████████████████████████████████████████████████████████████████████████████████████████| 23767/23767 [00:00<00:00, 31524.51ex/s]
Found cached dataset wikitext (/home/fritzprix/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2098.20it/s]
Traceback (most recent call last):
  File "/home/fritzprix/my_work/ml_note/labs/simple_ml/train.py", line 50, in <module>
    main(arg_parser.parse_args())
  File "/home/fritzprix/my_work/ml_note/labs/simple_ml/train.py", line 23, in main
    val_dataset = WikiDataset(n_steps=40, target='validate')
  File "/home/fritzprix/my_work/ml_note/labs/simple_ml/model/__init__.py", line 79, in __init__
    data = datasets.load_dataset('wikitext', 'wikitext-2-v1')[target]
  File "/home/fritzprix/miniconda3/envs/directml/lib/python3.10/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validate'